steps:
  - name: node:16
    entrypoint: npm
    args: ["install"]
  - name: node:16
    entrypoint: npm
    args: ["start"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "PORT=${_PORT}"
  - name: node:16
    entrypoint: npm
    args: ["run", "build"]
